#ifndef PLATFORMER_EVENT_DEFINES_H
#define PLATFORMER_EVENT_DEFINES_H

#include <SDL2/SDL_keycode.h>

#define KB_UNKNOWN SDLK_UNKNOWN

#define KB_BACKSPACE SDLK_BACKSPACE
#define KB_TAB SDLK_TAB
#define KB_RETURN SDLK_RETURN
#define KB_ESCAPE SDLK_ESCAPE

#define KB_SPACE SDLK_SPACE
#define KB_EXCLAIM SDLK_EXCLAIM
#define KB_QUOTEDBL SDLK_QUOTEDBL
#define KB_HASH SDLK_HASH
#define KB_DOLLAR SDLK_DOLLAR
#define KB_PERCENT SDLK_PERCENT
#define KB_AMPERSAND SDLK_AMPERSAND
#define KB_QUOTE SDLK_QUOTE
#define KB_LEFTPAREN SDLK_LEFTPAREN
#define KB_RIGHTPAREN SDLK_RIGHTPAREN

#define KB_ASTERISK SDLK_ASTERISK
#define KB_PLUS SDLK_PLUS
#define KB_COMMA SDLK_COMMA
#define KB_MINUS SDLK_MINUS
#define KB_PERIOD SDLK_PERIOD
#define KB_SLASH SDLK_SLASH

#define KB_CAPSLOCK SDLK_CAPSLOCK

#define KB_F1 SDLK_F1
#define KB_F2 SDLK_F2
#define KB_F3 SDLK_F3
#define KB_F4 SDLK_F4
#define KB_F5 SDLK_F5
#define KB_F6 SDLK_F6
#define KB_F7 SDLK_F7
#define KB_F8 SDLK_F8
#define KB_F9 SDLK_F9
#define KB_F10 SDLK_F10
#define KB_F11 SDLK_F11
#define KB_F12 SDLK_F12

#define KB_PRINTSCREEN SDLK_PRINTSCREEN
#define KB_SCROLLLOCK SDLK_SCROLLLOCK
#define KB_PAUSE SDLK_PAUSE
#define KB_INSERT SDLK_INSERT
#define KB_HOME SDLK_HOME
#define KB_PAGEUP SDLK_PAGEUP
#define KB_DELETE SDLK_DELETE
#define KB_END SDLK_END
#define KB_PAGEDOWN SDLK_PAGEDOWN

#define KB_RIGHT SDLK_RIGHT
#define KB_LEFT SDLK_LEFT
#define KB_DOWN SDLK_DOWN
#define KB_UP SDLK_UP

#endif // PLATFORMER_EVENT_DEFINES_H